display_denied_message: true
access_denied_message: 'Access denied. You must log in to view this page.'
redirect_authenticated_users_to: ''
user_login_path: 'user/login'
default_redirect_code:
  301: ''
  302: ''
match_noredirect_pages: ''
